# Site settings
baseURL = "https://www.wartimeaide.org/"
#baseURL = "/"
languageCode = "en-us"
title = "Wartime Aide"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-69113723-16"

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Wartime Aide"
  description = "Wartime Aide is a student-run Massachusetts charity focused on educating people about refugee issues."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "img/favicon.jpg"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Go back to [home page](/)."

  # Navigation Section
  [params.navigation]
    title = "Wartime Aide"
    subtitle = "Education is Power"
    menu = "Menu"
    # Optional logo as brand stored in img/
#    logo = "favicon.jpg"

    [[params.navigation.links]]
      name = "Home"
      url = "/"
    [[params.navigation.links]]
       name = "Members"
       url = "/members"

    [[params.navigation.links]]
      name = "Podcast"
      url = "/podcast"

    [[params.navigation.links]]
        name = "Who We Are"
        url = "/who-we-are"

    [[params.navigation.links]]
      name = "Join Us"
      url = "/join-us"

#    [[params.navigation.links]]
#      name = "Elements"
#      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Donate"
      url = "/donate"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Contact Us"
      url = "/contact-us"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Wartime Aide"
    subtitle = "Wartime Aide is a student-run Massachusetts charity focused on educating people about refugee issues."
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Our Mission"
      subtitle = "Our mission is to educate people about refugee issues."
      image = "backgrounds/7.webp"
      url = "/mission"

    [[params.tiles.showcase]]
      title = "Who We Are"
      subtitle = "A brief summary of our organization"
      image = "backgrounds/6.jpg"
      url = "/who-we-are"

#    [[params.tiles.showcase]]
#      title = "Donate"
#      subtitle = "100% of Your Donation Will Go Towards Wartime Aide's mission"
#      image = "backgrounds/1.jpg"
#      url = "/donate"

    [[params.tiles.showcase]]
      title = "Podcast"
      subtitle = "Listen to our New Podcast"
      image = "backgrounds/8.jpg"
      url = "/podcast"

    [[params.tiles.showcase]]
        title = "Join Us"
        subtitle = "Learn how to start a Wartime Aide chapter"
        image = "backgrounds/5.jpg"
        url = "/join-us"

#    [[params.tiles.showcase]]
#      title = "Etiam"
#      subtitle = "Feugiat Amet Tempus"
#      image = "pic06.jpg"
#      url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Donate"
    buttonText = "Donate"
    url = "/donate"

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
        title = "Email"
        email = "info@wartimeaide.org"

#    [[params.contact.phone]]
#    title = "Phone"
#    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
        title = "Address"
        street = "247 Marlborough Street"
        city = "Boston, MA 02459"
        country = "U.S.A."

  # Footer section
  [params.footer]
    enable = true
    copyright = "Wartime Aide Inc."

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/WartimeAide"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/wartimeaide/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/wartimeaide/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-youtube"
      url= "https://www.youtube.com/channel/UCRRmu_ZisafJz3_JVxa6xig"
      label = "YouTube"
#
#    [[params.footer.social]]
#      icon = "fa-linkedin"
#      url= "https://www.linkedin.com"
#      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
    [[params.footer.quicklinks]]
      text = "Powered By: "
      url= "https://www.netlify.com"
      alt = "Netlify"
